export const ADD_REGISTRATION_DATA = 'ADD_REGISTRATION_DATA';
export const ADD_LOGIN_DATA = 'ADD_LOGIN_DATA';
export const ADD_ASSISTANT_NAME_DATA = 'ADD_ASSISTANT_NAME_DATA';
export const ADD_ASSISTANT_STYLE_DATA = 'ADD_ASSISTANT_STYLE_DATA';
